### ISSUE TITLE
Collaboration is king

### ISSUE THREAD

**Issue by JKrag** [praqma-training/everyone-sdfe-12-2016#1]

**Comment by kbevers** [comment]
:+1:

**Comment by busstoptaktik** [comment]
Who's the queen, then?

**Comment by B027987** [comment]
top dollar

**Comment by taudorf** [comment]
Et eller andet

**Comment by Nikolpe** [comment]
hej

**Comment by heidivanparys** [comment]
en kommentar

**Comment by macwe** [comment]
Cool!

**Comment by MarkFizzel** [comment]
Hello Github!

**Comment by MartinHvidberg** [comment]
MartinHvidberg

**Comment by aan2603** [comment]
Her er Åge

**Comment by Pmja** [comment]
Kommentarer

**Comment by busstoptaktik** [comment]
## Glemte at

1. Teste *MarkDown*
2. Agurk

**Comment by Catje** [comment]
--

**Comment by hanne** [comment]
halløj

**Comment by mineisdfe** [comment]
Hej!

**Comment by Sonder79** [comment]
Test om det funger

**Comment by aeh123** [comment]
hej fra peter og anette

**Comment by JKrag** [comment]
:tada: @kbevers, @busstoptaktik, @B027987, @taudorf, @Nikolpe, @heidivanparys, @macwe, @MarkFizzel, @MartinHvidberg, @aan2603, @Pmja, @busstoptaktik, @Catje, @hanne, @mineisdfe, and @Sonder79 are now  repository collaborators. :balloon:

**Comment by JKrag** [comment]
* lister
* 

:100:
